[package]
name = "justwhitee-notes"
version = "0.1.0"
entrypoint = "lib.typ"
authors = [ "Matteo Fontolan <justwhitee>" ]
compiler = "0.12.0"
description = "Modern justwhitee-like template for notes."
categories = [ "model", "text" ]
disciplines = [ "computer-science", "engineering" ]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.jpg"
